services:
  - type: web
    name: flask
    env: python
    plan: free
    branch: main
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    runtime: python
    pythonVersion: 3.11.9
